stages:
  data_ingestion:
    cmd: python src/DeepClassifier/pipeline/data_ingestion_stage1.py
    deps:
      - src/DeepClassifier/pipeline/data_ingestion_stage1.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages

  prepare_base_model:
    cmd: python src/DeepClassifier/pipeline/prepare_base_model_stage2.py 
    deps:
      - src/DeepClassifier/pipeline/prepare_base_model_stage2.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/DeepClassifier/pipeline/training_stage3.py
    deps:
      - src/DeepClassifier/pipeline/training_stage3.py
      - src/DeepClassifier/components/prepare_callback.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/DeepClassifier/pipeline/evaluation_stage_04.py
    deps:
      - src/DeepClassifier/pipeline/evaluation_stage_04.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
        